Xmax: 110.94490051269531
batch_size: 256
beta: 0
db_min_norm: -60
decoder_layers: !!python/tuple
- 8
- 16
- 32
- 64
- 128
- 256
- 512
- 1024
- 1025
encoder_layers: !!python/tuple
- 1025
- 1024
- 512
- 256
- 128
- 64
- 32
- 16
- 8
- 4
epochs: 1000
hop_length: 512
latent_dim: 4
learning_rate: 0.001
loss: MAE + KL
normalize_each_audio: false
parameters: 3512647
spec_in_db: true
target_sampling_rate: 22050
win_length: 2048
